// Lifecycle Method =>
// 1.Mounting
import React, { Component } from "react";
export default class Mount extends Component {
    // 1.First Method
    constructor() {
        super()
        this.state = {
            message: "hello Good Morning"
        }
        console.log("constructor")
    }

    // 2. Second Method
    static getDerivedStateFromProps(props) {
        console.log("static")
        return null

    }

    // 4. Fourth Method
    componentDidMount() {
        console.log("Did Mount")
        setTimeout(() => {
            this.setState({
                message: "Message generated by componetDidMount Method"
            })
        }, 3000);
    }
    // 3. Third Method
    render() {
        console.log("render method")
        return <p>Message:{this.state.message}</p>
    }
}